# Generated by Django 4.1.4 on 2022-12-14 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, null=True)),
                ("company_address", models.CharField(max_length=200, null=True)),
                ("industry", models.CharField(max_length=200, null=True)),
                ("phone_number", models.CharField(max_length=200, null=True)),
                ("email_address", models.CharField(max_length=200, null=True)),
                ("website", models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tender",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("category", models.CharField(max_length=200, null=True)),
                ("description", models.TextField(null=True)),
                ("budget", models.IntegerField(null=True)),
                ("opening_date", models.DateTimeField()),
                ("deadline", models.DateTimeField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contractor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, null=True)),
                ("company_address", models.CharField(max_length=200, null=True)),
                ("industry", models.CharField(max_length=200, null=True)),
                ("phone_number", models.CharField(max_length=200, null=True)),
                ("email_address", models.CharField(max_length=200, null=True)),
                ("website", models.CharField(max_length=200, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bids",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField(max_length=200, null=True)),
                ("bid_price", models.IntegerField(null=True)),
                ("submission_date", models.DateTimeField(max_length=50)),
                (
                    "supplier_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.supplier"
                    ),
                ),
                (
                    "tender_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tender"
                    ),
                ),
            ],
        ),
    ]
