# Generated by Django 4.1.4 on 2022-12-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenders",
            name="contractor_id",
        ),
        migrations.AlterField(
            model_name="bids",
            name="bid_price",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="tenders",
            name="budget",
            field=models.IntegerField(null=True),
        ),
    ]
