# Generated by Django 4.1.4 on 2023-01-06 10:11

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_managers_remove_user_username_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[(1, "CONTRACTOR"), (2, "SUPPLIER"), (3, "ADMIN")],
                default=core.utils.UserType["CONTRACTOR"],
                max_length=20,
            ),
        ),
    ]
