# Generated by Django 4.1.4 on 2022-12-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_tenders_contractor_id_alter_bids_bid_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenders",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
