# Generated by Django 4.1.4 on 2022-12-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_tenders_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenders",
            name="deadline",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="tenders",
            name="opening_date",
            field=models.DateTimeField(),
        ),
    ]
