# Generated by Django 4.1.4 on 2022-12-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_tenders_deadline_alter_tenders_opening_date"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tenders",
            new_name="Tender",
        ),
    ]
