# Generated by Django 4.1.4 on 2023-01-09 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_bids_supplier_alter_tender_contractor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bids",
            old_name="supplier",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="tender",
            old_name="contractor",
            new_name="owner",
        ),
    ]
