# Generated by Django 4.1.4 on 2023-01-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_rename_supplier_bids_owner_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tender",
            old_name="description",
            new_name="requirement_details",
        ),
        migrations.AddField(
            model_name="tender",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="tender",
            name="notice_number",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
