# Generated by Django 4.1.4 on 2023-01-10 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_rename_description_tender_requirement_details_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bids",
            name="tender_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to="core.tender",
            ),
        ),
    ]
