# Generated by Django 4.1.4 on 2023-01-11 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_bids_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tender",
            old_name="name",
            new_name="tender_name",
        ),
    ]
