# Generated by Django 4.1.4 on 2023-01-11 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_rename_name_tender_tender_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tender",
            name="owner",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
