# Generated by Django 4.1.4 on 2023-01-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_tender_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tender",
            name="id",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
