# Generated by Django 4.1.4 on 2023-01-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_tender_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tender",
            name="id",
            field=models.CharField(
                default=None, max_length=100, primary_key=True, serialize=False
            ),
        ),
    ]
