# Generated by Django 4.1.4 on 2023-01-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_tender_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bids",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
