# Generated by Django 4.1.4 on 2023-01-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_tender_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bids",
            name="owner",
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="tender",
            name="owner",
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
