# Generated by Django 4.1.4 on 2023-01-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_alter_bids_owner_alter_tender_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bids",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
